##################################
#                                #
#           Redis-Homes          #
#          v1.0 by DevSnx        #
#                                #
##################################

# Language (en, de)
lang: en

# Redis Server Connection
redis:
  host: redis
  port: 6379
  username: "snx"
  password: "Wa9AwE4dLP,c2äü"

# MySQL Server Connection
mysql:
  host: "127.0.0.1"
  port: 6379
  username: "root"
  password: "docker"
  database: "homes"
  poolSize: 10