##################################
#                                #
#           Redis-Homes          #
#          v1.0 by DevSnx        #
#                                #
##################################

# Redis Server Connection
redis:
  host: redis
  port: 6379
  username: "snx"
  password: "Wa9AwE4dLP,c2äü"

# MySQL Server Connection
mysql:
  host: mariadb
  port: 3306
  username: "root"
  password: "docker"
  database: "homes"